export const SET_COMPANIES_ARRAY = 'SET_COMPANIES_ARRAY';
export const CHANGE_TABLE_HEADER_FILTER = 'CHANGE_TABLE_HEADER_FILTER';
export const CHANGE_PAGINATION_INDEXES_OF_ARRAY_OF_COMPANIES = 'CHANGE_PAGINATION_INDEXES_OF_ARRAY_OF_COMPANIES';
export const SET_FILTERED_ARRAY_BY_TEXT_INPUT = 'SET_FILTERED_ARRAY_BY_TEXT_INPUT';
export const CHANGE_DISPLAYING_ARRAY = 'CHANGE_DISPLAYING_ARRAY';